name: BDD Tests

on:
  pull_request:
    branches: [ main ]
  workflow_dispatch:
  push:
    paths:
      - 'features/**'
      - 'src/**'
      - 'package.json'
      - 'cucumber.js'

jobs:
  bdd-tests:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Run BDD Tests
        run: |
          mkdir -p reports
          export NODE_ENV=test
          npm run test:bdd:ci
      
      - name: Upload BDD test report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: bdd-test-report-${{ github.run_id }}
          path: reports/cucumber-report.json
          retention-days: 7
      
      - name: Generate BDD test summary
        if: always()
        run: |
          if [ -f reports/cucumber-report.json ]; then
            echo "## BDD Test Results" >> $GITHUB_STEP_SUMMARY
            echo "" >> $GITHUB_STEP_SUMMARY
            
            # Parse the JSON report to extract test results
            total=$(jq '[.[] | .elements | length] | add' reports/cucumber-report.json)
            passed=$(jq '[.[] | .elements[] | select(.steps | all(.result.status == "passed")) | 1] | add // 0' reports/cucumber-report.json)
            failed=$(jq '[.[] | .elements[] | select(.steps | any(.result.status == "failed")) | 1] | add // 0' reports/cucumber-report.json)
            pending=$(jq '[.[] | .elements[] | select(.steps | any(.result.status == "undefined" or .result.status == "pending")) | 1] | add // 0' reports/cucumber-report.json)
            
            echo "- **Total Scenarios**: $total" >> $GITHUB_STEP_SUMMARY
            echo "- **Passed**: $passed ✅" >> $GITHUB_STEP_SUMMARY
            echo "- **Failed**: $failed ❌" >> $GITHUB_STEP_SUMMARY
            echo "- **Pending**: $pending ⏳" >> $GITHUB_STEP_SUMMARY
            echo "" >> $GITHUB_STEP_SUMMARY
            
            # List failed scenarios if any
            if [ "$failed" -gt 0 ]; then
              echo "### Failed Scenarios" >> $GITHUB_STEP_SUMMARY
              jq -r '.[] | .elements[] | select(.steps | any(.result.status == "failed")) | "- \(.name) (in \(.keyword): \(.description // "No description"))"' reports/cucumber-report.json >> $GITHUB_STEP_SUMMARY
            fi
          else
            echo "No BDD test report found" >> $GITHUB_STEP_SUMMARY
          fi